---
title: "NUM-25-01-03"
output: html_document
date: "2026-02-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
NewtonPolynomialCoefs <- function(x, y){
  N <- length(x)
  a <- y
  if(N == 1) return(a)
  a[2] <- (y[2]-y[1])/(x[2]-x[1])
  if(N == 2) return(a)
  for(i in 3:N){
    suma <- y[i]
    soucin <- 1
    for(j in 1:(i-1)){
      suma <- suma - a[j]*soucin
      soucin <- soucin*(x[i]-x[j])
    }
    a[i] <- suma/soucin
  }
  return(a)
}
```
```{r}
# Data ze zadání
p <- c(0.1, 0.2, 0.28, 0.41, 0.98, 1.39, 1.93, 2.75, 3.01, 3.51) 
a <- c(0.089, 0.127, 0.144, 0.163, 0.189, 0.198, 0.206, 0.208, 0.209, 0.210) 

# Linearizace pro MNC
x_lin <- 1/p
y_lin <- 1/a

# Výpočet koeficientů lineární regrese
n <- length(p)
ss_x <- sum(x_lin)
ss_y <- sum(y_lin)
ss_xx <- sum(x_lin^2)
ss_xy <- sum(x_lin * y_lin)

# Řešení soustavy normálních rovnic pro k a q
k <- (n * ss_xy - ss_x * ss_y) / (n * ss_xx - ss_x^2)
q <- (ss_y - k * ss_x) / n

# Zpětný převod na parametry modelu
am <- 1/q
b_param <- 1/(am * k)
```
```{r}
# Použijeme NewtonPolynomialCoefs a poly_val definované dříve
coefs_poly <- NewtonPolynomialCoefs(p, a)
```
```{r}
# Funkce pro hledání průsečíku
f_rozdil <- function(p_val) {
  a_mod <- am * (b_param * p_val) / (1 + b_param * p_val)
  a_poly <- poly_val(p, coefs_poly, p_val)
  return(a_mod - a_poly)
}

# Hledání největšího průsečíku (poblíž p = 3.5)
# Bisekce na intervalu [3.0, 3.51]
low <- 3.0; high <- 3.51
for(i in 1:20) {
  mid <- (low + high) / 2
  if(f_rozdil(low) * f_rozdil(mid) < 0) high <- mid else low <- mid
}
cat("Největší průsečík leží v p =", round(mid, 4)) 
```