---
title: "num111"
output: html_document
date: "2026-02-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
Romberg <- function(f, a, b, n = 2){
  m <- 2^n
  h <- (b-a)/m
  x <- a + h*(1:(m-1))
  y <- f(x)
  res <- numeric(n)
  
  odd <- seq(1, m, 2)
  pocetHodnot <- m
  for(i in n:1){
    h <- 2*h
    pocetHodnot <- pocetHodnot/2
    sekvence <- odd[1:pocetHodnot]
    res[i] <- h * sum(y[sekvence])
    y <- y[-sekvence]
  }
  A <- matrix(0, nrow=n, ncol=n)
  A[, 1] <- res
  nasobic <- 1
  for(i in 2:n){
    nasobic <- nasobic*4
    A[i:n, i] <- (nasobic*A[i:n, i-1]-A[(i-1):(n-1), i-1])/(nasobic-1)
  }
  return(A)
  # 1, 3, 5, 7, 9, 11, 13, 15
  # 2, 6, 10, 14
  # 4, 12
  # 8
}
GausovaEliminaceSPivotaci <- function(A, b, N){
  Ab <- cbind(A, b)
  # primy chod
  for(p in 1:(N-1)){
    pmax <- which.max(abs(Ab[p:N, p])) + p - 1
    if(pmax != p){
      j <- p:(N+1)
      aux <- Ab[p, j]
      Ab[p, j] <- Ab[pmax, j]
      Ab[pmax, j] <- aux
    }
    prec <- 1/Ab[p, p]
    for(i in (p+1):N){
      j <- (p+1):(N+1)
      Ab[i, j] <- Ab[i, j] - Ab[i, p] * prec * Ab[p, j]
    }
  }
  # zpetny chod
  x <- numeric(N)
  A <- Ab[, -(N+1)]
  b <- Ab[, N+1]
  x[N] <- b[N]/A[N, N]
  for(i in (N-1):1){
    j <- (i+1):N
    x[i] <- (b[i] - sum(A[i, j]*x[j]))/A[i, i]
  }
  return(x)
}
NewtonPolynomialCoefs <- function(x, y){
  N <- length(x)
  a <- y
  if(N == 1) return(a)
  a[2] <- (y[2]-y[1])/(x[2]-x[1])
  if(N == 2) return(a)
  for(i in 3:N){
    suma <- y[i]
    soucin <- 1
    for(j in 1:(i-1)){
      suma <- suma - a[j]*soucin
      soucin <- soucin*(x[i]-x[j])
    }
    a[i] <- suma/soucin
  }
  return(a)
}
simpson <- function(x_base, coefs, a, b, m = 100) {
  h <- (b - a) / m
  x_vals <- seq(a, b, by = h)
  y_vals <- sapply(x_vals, function(v) poly_val(x_base, coefs, v))
  
  s <- y_vals[1] + y_vals[m + 1] + 
    4 * sum(y_vals[seq(2, m, by = 2)]) + 
    2 * sum(y_vals[seq(3, m - 1, by = 2)])
  return(s * h / 3)
}
```
```{r}
n = 10
A = matrix(nrow = n, ncol = n)
y = c(1:10)
A_value <- function(i, j) cos((i - 1) * j) - j
y_value <- function(i) sin(i)
for(i in 1:n) {
  y[i] = y_value(i)
  for(j in 1:n) {
    A[i, j] = A_value(i, j)
  }
}
# 1
x = GausovaEliminaceSPivotaci(A, y, n)
```
```{r}
# 2
p <- NewtonPolynomialCoefs(x, y)
# Výpočet hodnoty polynomu v bodě (Hornerovo schéma)
poly_val <- function(x_base, coefs, x_target) {
  n <- length(coefs)
  res <- coefs[n]
  for (i in (n - 1):1) {
    res <- res * (x_target - x_base[i]) + coefs[i]
  }
  return(res)
}

p_zero = poly_val(x, p, 0)
p_zero
RK4 <- function(f, x, y, h){
  hpul <- 0.5*h
  xpul <- x+hpul
  k1 <- f(x,y)
  k2 <- f(xpul,y+hpul*k1)
  k3 <- f(xpul,y+hpul*k2)
  k4 <- f(x+h, y+h*k3)
  return(y+h*(k1+2*(k2+k3)+k4)/6)
}
simpson(x, p, min(x), max(x))
```
```{r}
vnitrni_f <- function(a) 1-exp(-2*a*pi)/a^2+1




```